SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT 
        FI.ID, 
        FNI.FISH_NAME, 
        FI.LENGTH,
        ROW_NUMBER() OVER (PARTITION BY FI.FISH_TYPE ORDER BY FI.LENGTH DESC) AS RN
    FROM FISH_INFO FI
    JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
) T
WHERE RN = 1
ORDER BY ID ASC;